import{a as w,S,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",q="50786624-1add8080b253d44feed6410de";async function u(t,o){try{return(await w.get(v,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch{iziToast.error({title:"Error",message:"Something went wrong. Try again later.",position:"center"})}}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".button-more"),E=new S(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.3});function h(t){const o=t.map(({webformatURL:i,largeImageURL:c,tags:e,likes:r,views:a,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${i}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${L}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){m.innerHTML=""}function y(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}function P(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}const R=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]'),B=document.querySelector(".button-more");let s=1,d="";R.addEventListener("submit",O);async function O(t){t.preventDefault();const o=$.value.trim();if(!o){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}d=o,s=1,M(),l(),y();try{const i=await u(d,s);if(i.hits.length===0){n.warning({title:"No Results",message:"Sorry, no images match your query.",position:"center"});return}h(i.hits),s*15>=i.totalHits?(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):P()}catch{n.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{g()}}B.addEventListener("click",T);async function T(){s+=1,y();try{const t=await u(d,s);h(t.hits),x(),s*15>=t.totalHits&&(l(),n.info({title:"End ",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}}function x(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
